spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_app_db?schema=public
    username: postgres
    password: postgres
  jpa:
    show-sql: true

logging:
    ru:
      smartech:
        app: debug